### ISSUE TITLE
Change playlist?

### ISSUE THREAD

**Issue by wormiedk** [natekspencer/hacs-oasis_mini#23]
Is it possible to change the playlist from the integration e.g. add or remove items from the playlist?

**Comment by natekspencer** [comment]
Right now, there is not a way to remove an individual track from the playlist. You can add a track or clear the playlist. An example of clearing the playlist and starting a new track is below:

```yaml
action: media_player.play_media
target:
  entity_id:
    - media_player.oasis_mini # use your specific entity_id if it is not this
data:
  media_content_id: A Star # this can be a track id such as 131, or a track title that it will try to look up
  enqueue: replace # "replace" will clear the playlist and add the new track. You can also use "play", "next", or "add"
  media_content_type: track # this is ignored, but required for the media_player.play_media action
```
